### ISSUE TITLE
Named Parameters

### ISSUE THREAD

**Issue by shadowhand** [Thavarshan/fetch-php#3]
### Description

Changed the array blob of options to named parameters. 

### Feature Details

It does not make sense to use an array, which has little type safety and little ability to type hint, when named parameters are available and make it much safer and more efficient to allow many options. 

#### Additional Information

If this is an acceptable request, I am happy to work on it.

Cool project!

**Comment by Thavarshan** [comment]
Hiya! 

Thanks for bringing this up! I totally agree with your points — using named parameters definitely makes things much clearer and safer. Hindsight, right? 😄

I am working on a new major release with a fluent api but it not going to be ready for a while. So, feel free to start working on it if you'd like. Looking forward to seeing what you come up with!

P. S. extra points if you can make it backwards compatible as well I'll also consider you a star! ⭐🤩

**Comment by Thavarshan** [comment]
Closing in faour of fluent API add in `v2.0.0`
