### ISSUE TITLE
Can't Install in Laravel 10

### ISSUE THREAD

**Issue by arif98741** [Thavarshan/fetch-php#5]
- Laravel Version: 10.48.22
- PHP Version: 8.2.0

### Description
I was trying to install in laravel 10. But it creates issues while installing
![image](https://github.com/user-attachments/assets/64a1fec9-8df1-428a-9503-f5d45ff098ad)

### Steps To Reproduce
```
composer create-project --prefer-dist laravel/laravel demo10 10.*
cd demo10
composer require jerome/fetch-php

```

**Comment by Thavarshan** [comment]
Noted! I'll release a patch for this. Apologies for the inconveniences!

**Comment by arif98741** [comment]
> Noted! I'll release a patch for this. Apologies for the inconveniences!

No worry . Waiting for the release

**Comment by Thavarshan** [comment]
@arif98741 just letting you know I've attempted a patch for this issue in `v1.1.1`. Let me know if it has fixed it.

**Comment by Thavarshan** [comment]
@arif98741 just to give you an update, I'm still investigating this issue. I can reproduce it but still trying to figure out how to fix this. Any assistance will be greatly appreciated! 😁

**Comment by Thavarshan** [comment]
@arif98741 I think I've managed to fix it. I have not made a new release but I have made a re-release of `v1.1.1`. Would appreciate some feedback on this please? 🙂

**Comment by arif98741** [comment]
Ok. Let me check that pre release

**Comment by arif98741** [comment]
It's successfully installed in `laravel 10` without any issue 🔥

**Comment by Thavarshan** [comment]
Closing this issue, but will re-open if someone else has the same issue even after the fix.
